ALTER SESSION SET NLS_DATE_LANGUAGE = 'ITALIAN';

@@DROP_TABLE.sql
@@DROP_VIEW.sql
@@CREATE_TABLE.sql
@@DCL_UTENTI.sql
@@POPOLA_TABELLE.sql
@@TR_ANIMALE.sql
@@TR_ASSISTE.sql
@@TR_CONSEGNA.sql
@@TR_LATTE.sql
@@TR_PERSONA.sql
@@TR_PRODOTTO.sql
@@TR_PROMOZIONE.sql
@@TR_TESSERA.sql
@@TR_TURNOLAVORATIVO.sql
@@TR_UTILIZZA.sql
@@CALCOLA_SCONTO.sql
@@GENERA_TURNO_LAVORATIVO.sql
@@RINNOVO_CERTIFICATO.sql
@@RINNOVO_TESSERA.sql
@@SOSTITUISCI_CASSIERE.sql
@@SOSTITUISCI_VEICOLO.sql
@@CLASSIFICA_CLIENTI.sql
@@ANDAMENTO_PROMO.sql
@@REPORT_VEICOLI.sql
@@DROP_TL_DELETE_DATA.sql
@@TL_DELETE_DATA.sql

CL SCR;

PROMPT Operazione completata.